# Generated by Django 3.2.21 on 2024-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productQuantity', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
