# Generated by Django 3.2.21 on 2024-02-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_poducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poducts',
            new_name='Products',
        ),
    ]
