# Generated by Django 3.2.21 on 2024-02-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_poducts_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='username',
            new_name='price',
        ),
    ]
